services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony-php
    volumes:
      - ./:/var/www/symfony
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
